Repository Ktechen/Dripbox, pull requests merged in 2021-10, with the labels that each got.

#84 Adds better design to existing Chatroom site
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/chatrooms.scss
  app/assets/stylesheets/rooms.scss
  app/views/rooms/index.html.erb
Labels: bug

#66 Feature/statistics and more
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/password_resets.scss
  app/assets/stylesheets/registrations.scss
  app/assets/stylesheets/sessions.scss
  app/assets/stylesheets/statistics.scss
  app/assets/stylesheets/user_resources.scss
  app/controllers/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/user_resources_controller.rb
  app/helpers/userpage_helper.rb
  app/javascript/channels/consumer.js
  app/javascript/packs/application.js
  app/javascript/packs/statistics_scripts/file_size_classification.js
  app/javascript/packs/statistics_scripts/file_type_classification.js
  app/javascript/packs/statistics_scripts/missing/missing_file_size_classification.js
  app/javascript/packs/statistics_scripts/missing/missing_file_type_classification.js
  app/javascript/packs/statistics_scripts/missing/missing_upload_files_history.js
  app/javascript/packs/statistics_scripts/upload_files_history.js
  app/javascript/src/PasswordHandler.js
  app/models/user.rb
  app/models/user_resource.rb
  app/views/contact_mailer/send_information.text.erb
  app/views/contacts/new.html.erb
  app/views/dashboard/index.html.erb
  app/views/layouts/_logging_btn.html.erb
  app/views/layouts/_logout.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
  app/views/resources/_recent_files_list.html.erb
  app/views/search/index.html.erb
  app/views/site_informations/agb.html.erb
  app/views/site_informations/datenschutz.html.erb
  app/views/statistics/_file_size_classification.html.erb
  app/views/statistics/_file_type_classification.html.erb
  app/views/statistics/_upload_file_history.html.erb
  app/views/statistics/_user_statistics_section.erb
  app/views/user_resources/_form.html.erb
  app/views/user_resources/index.html.erb
  app/views/user_resources/new.html.erb
  app/views/user_resources/show.html.erb
  db/migrate/20210527200903_create_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/dashboard_controller_test.rb
  test/controllers/user_resources_controller_test.rb
  test/models/user_resource_test.rb
  test/models/user_statistics_method_test.rb
  test/system/dashboards_test.rb
Labels: enhancement

#86 Fix/dashboard mobile css
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/dashboard.scss
  app/views/dashboard/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
Labels: visual-bug

#92 Fix/darkmode initial login
  app/controllers/application_controller.rb
Labels: bug, visual-bug

#94 Fix/tag save failure
  app/assets/stylesheets/dashboard.scss
  app/controllers/user_resources_controller.rb
  app/models/tag.rb
  app/models/user_resource.rb
  app/views/user_resources/_form.html.erb
  app/views/user_resources/show.html.erb
  test/controllers/user_resources_controller_test.rb
  test/models/tag_test.rb
  test/models/user_resource_test.rb
Labels: bug

#98 Fix/search site
  app/assets/stylesheets/search_results.scss
  app/controllers/search_controller.rb
  app/models/user_resource.rb
  app/views/search/index.html.erb
Labels: enhancement

#104 Fix/make dashboard links to buttons
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/dashboard.scss
  app/views/dashboard/index.html.erb
Labels: bug, visual-bug
