Repository Ktechen/Dripbox, pull requests merged in 2021-09, with the labels that each got.

#45 put footer in layout flow with static positioning
  app/assets/stylesheets/footer.scss
Labels: bug

#46 Auto redirect login
  app/controllers/application_controller.rb
  app/controllers/home_pages_controller.rb
  app/views/home_pages/_home_page.html.erb
Labels: enhancement

#48 add jquery and graphics-metrics libraries over yarn add
  package.json
  yarn.lock
Labels: enhancement

#49 give content-wrap min-height of the screen
  app/assets/stylesheets/application.scss
Labels: visual-bug

#51 update css and dashboard view for new header and footer format
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/dashboard.scss
  app/views/dashboard/index.html.erb
Labels: visual-bug

#56 add bootstrap in yarn
  app/assets/stylesheets/application.scss
  app/javascript/packs/application.js
  app/views/layouts/application.html.erb
  package.json
  yarn.lock
Labels: bug, visual-bug

#58 add bootstrap over yarn
  package.json
  yarn.lock
Labels: bug, visual-bug

#62 Feature/language
  app/controllers/application_controller.rb
  app/views/dashboard/index.html.erb
  app/views/home_pages/_home_page.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_logging_btn.html.erb
  app/views/password_resets/new.html.erb
  app/views/registrations/_signup.html.erb
  app/views/resources/_categories_listing.html.erb
  app/views/resources/_recent_files_list.html.erb
  app/views/resources/_selected_file_listing.html.erb
  app/views/user_mailer/confirm_your_email.html.erb
  app/views/user_mailer/forgot_password.text.erb
  app/views/user_mailer/index.html.erb
  app/views/user_mailer/registration_confirmation.text.erb
  app/views/user_resources/_form.html.erb
  app/views/user_resources/edit.html.erb
  app/views/user_resources/index.html.erb
  app/views/user_resources/new.html.erb
  app/views/user_resources/show.html.erb
  app/views/users/confirm_email.html.erb
  config/application.rb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/pepe.yml
  package-lock.json
  test/locales/language_change.rb
Labels: feature

#63 Fix Session Controller Test
  test/controllers/sessions_controller_test.rb
Labels: bug

#61 Feature/contacts
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/contacts.scss
  app/controllers/contacts_controller.rb
  app/controllers/users_controller.rb
  app/helpers/contacts_helper.rb
  app/mailers/contact_mailer.rb
  app/models/contact.rb
  app/views/contact_mailer/send_information.text.erb
  app/views/contact_mailer/send_to_management.text.erb
  app/views/contacts/create.html.erb
  app/views/contacts/index.html.erb
  app/views/contacts/new.html.erb
  app/views/dashboard/index.html.erb
  app/views/home_pages/_home_page.html.erb
  app/views/layouts/_back_to_dashboard.html.erb
  app/views/layouts/_error_messages.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/password_resets/edit.html.erb
  app/views/registrations/_signup.html.erb
  app/views/users/edit.html.erb
  config/routes.rb
  db/migrate/20210821150812_create_contacts.rb
  db/migrate/20210821185834_add_contactable_to_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/contacts_controller_test.rb
  test/fixtures/contacts.yml
  test/mailers/contact_mailer_test.rb
  test/mailers/previews/contact_mailer_preview.rb
  test/models/contact_test.rb
Labels: feature

#65 Feature/darkmode lightmode
  Gemfile.lock
  app/assets/images/darkmode.png
  app/assets/images/lightmode.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/header.scss
  app/assets/stylesheets/site_informations.scss
  app/controllers/application_controller.rb
  app/models/user_resource.rb
  app/views/contacts/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/site_informations/about.html.erb
  app/views/site_informations/datenschutz.html.erb
  app/views/users/edit.html.erb
  config/environments/production.rb
  test/integration/dark_light_mode_test.rb
Labels: enhancement
